# Generated by Django 2.2 on 2020-11-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserentity',
            name='password',
        ),
    ]
