# Generated by Django 2.2 on 2020-11-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201106_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageentity',
            old_name='custom_user_entity',
            new_name='custom_user_entity_id',
        ),
    ]
