# Generated by Django 2.2 on 2020-11-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20201106_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageentity',
            old_name='custom_user_entity_id',
            new_name='custom_user_entity',
        ),
    ]
